In [1]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
text=['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']
len(text) # 11개의 문장 

11

In [3]:
stopwords.words('english') # 영어 불용어

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [4]:
vocab = {} #딕셔너리
sentences =[]
stop_words = set(stopwords.words('english')) # 중복 제외한 set

# text는 총 11개의 문장

for i in text:
    sentence = word_tokenize(i) # 문장 i를 단어 토큰화
    result = []
    for word in sentence:
        word = word.lower() # 모든 단어 소문자화
        if word not in stop_words:
            if len(word)>2: 
                result.append(word) # 불용어에 없고, 길이가 2보다 크면 word에 append
                if word not in vocab:
                    vocab[word] = 0 # vocab에 없는 새로운 단어라면 초기화
                vocab[word] += 1    # 원래 있던 단어라면 +1
    sentences.append(result)
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [5]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [6]:
sorted(vocab.items()) # key값으로 sort
sorted(vocab.items(),reverse=True) #key값 내림차순 sort
vocab_sorted = sorted(vocab.items(),reverse=True,key=lambda x:x[1])
# key : 정렬기준, key가 x[1] >> 빈도수 기준 정렬

In [7]:
vocab_sorted

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [8]:
word_to_index = {}
i = 0
for (word,freq) in vocab_sorted: # vocab_sorted에는 빈도 높은 단어 순으로 정렬
    if freq > 1:                 
        i+=1
        word_to_index[word] = i  # 가장 높은 freq의 단어부터 value가 1부터 채워짐 
word_to_index        

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7}

In [9]:
# 빈도수가 가장 높은 n개 단어 추출
vs = 5

# vs개만큼의 단어들만 추출
[w[0] for w in word_to_index.items() if w[1] <= vs]

['barber', 'secret', 'huge', 'kept', 'person']

In [10]:
# 인덱스가 5가 넘는 단어 제거
[w[0] for w in word_to_index.items() if w[1]>vs]
words_freq = [w for w,c in word_to_index.items() if c>vs] # index가 5 넘으면 w
words_freq

['word', 'keeping']

In [11]:
for w in words_freq:
    del word_to_index[w]
word_to_index['OOV'] = len(word_to_index)+1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [12]:
# sentences(텍스트)의 단어중에서 word_to_index(Corpus)에 없는 단어는 OOV라고함
# Out Of Vocabulary

In [13]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [14]:
encoded = []
for s in sentences:
    temp = []
    for w in s: #각각의 단어들이 w로
        try:
            temp.append(word_to_index[w])
        except KeyError: # error 제목  >> 없는 key는 OOV로 
            temp.append(word_to_index['OOV'])
    encoded.append(temp)
print(encoded)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [31]:
from collections import Counter # 갯수세는 package

In [23]:
sentences
words = []

for word in sentences:
    for w in word:
        words.append(w)
print(words)

words= sum(sentences,[])
print(words)

import numpy as np
words = np.hstack(sentences)
words

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']
['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


array(['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge',
       'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret',
       'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept',
       'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge',
       'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge',
       'mountain'], dtype='<U8')

In [24]:
Counter(words)

Counter({'barber': 8,
         'person': 3,
         'good': 1,
         'huge': 5,
         'knew': 1,
         'secret': 6,
         'kept': 4,
         'word': 2,
         'keeping': 2,
         'driving': 1,
         'crazy': 1,
         'went': 1,
         'mountain': 1})

In [44]:
vocab = Counter(words)
print(vocab['barber'])
vocab

8


Counter({'barber': 8,
         'person': 3,
         'good': 1,
         'huge': 5,
         'knew': 1,
         'secret': 6,
         'kept': 4,
         'word': 2,
         'keeping': 2,
         'driving': 1,
         'crazy': 1,
         'went': 1,
         'mountain': 1})

In [50]:
vocab = vocab.most_common(5) # 빈도수가 가장높은 5개 단어
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [52]:
i=0
word_to_index={}
for (w,f) in vocab:
    i = i+1
    word_to_index[w] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
'''
법령코퍼스={헌법:1, 피고인:2, ..., OOV:1000}
OOV?자연어, 물, 컵,.., 경범죄
'''

In [58]:
from nltk import FreqDist

In [73]:
vocab=FreqDist(np.hstack(sentences))
#r장 빈도수가 많은 단어를 튜플 리스트로 (단어, 빈도수) 형태로 뽑아낸다.
vocab
vocab['barber']

8

In [74]:
vocab=vocab.most_common(vs)

In [75]:
for i,w in enumerate(vocab): # enumerate > 열거
    print(i,w)

0 ('barber', 8)
1 ('secret', 6)
2 ('huge', 5)
3 ('kept', 4)
4 ('person', 3)


In [76]:
# enumerate로 word_to_index
word_to_index = {w[0]:i+1 for i,w in enumerate(vocab)}
word_to_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [57]:
## 패딩:문장의 길이 동일하게...

In [92]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [93]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [94]:
tokenizer = Tokenizer()

In [95]:
tokenizer.fit_on_texts(sentences) # 일반적인 문장들(text)에 대해서 수치화

In [96]:
encoded = tokenizer.texts_to_sequences(sentences) # 
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [100]:
[len(i) for i in encoded]

[2, 3, 3, 2, 4, 2, 3, 3, 3, 7, 4]

In [101]:
max_len= max([len(i) for i in encoded])

In [102]:
# 왼쪽에 패딩, 오른쪽에 패딩
[3,1,5,0,0,0,0] # 우측 패딩
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [103]:
for item in encoded:
    while len(item) < max_len:
        item.append(0)
print(encoded)

[[1, 5, 0, 0, 0, 0, 0], [1, 8, 5, 0, 0, 0, 0], [1, 3, 5, 0, 0, 0, 0], [9, 2, 0, 0, 0, 0, 0], [2, 4, 3, 2, 0, 0, 0], [3, 2, 0, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 2, 0, 0, 0, 0], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13, 0, 0, 0]]


In [107]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [110]:
encoded= tokenizer.texts_to_sequences(sentences)

In [111]:
pad_sequences(encoded) # default >> 왼쪽에 패딩 

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]])

In [112]:
pad_sequences(encoded,padding='post')

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

### NLP - One Hot Encoding  

- 장점이자 단점 : 모든 단어의 유사도를 0으로 만듬
- 데이터의 특성을 유지한 상태로 벡터 공간에 투영 > 임베딩

In [ ]:
# 단어집합(자연어, 처리, 파이썬,..) -> 정수인코딩(1,2,3...) -> 원핫인코딩(단어 집합의 크기를 벡터의 차원으로 간주)
# 10차원 벡터(단어가 10개, 인덱스:1~10번까지)에서 해당 단어의 위치에는 1을 주고, 나머지에는 0을 주는 방식
# 단어를 벡터 형태로 표현하게 됨.

In [ ]:
'''
자연어:1, 처리:2, 파이썬:3, ... 물:10
자연어 ->1000000000
처리 -> 0100000000
...
물 -> 0000000001
'''

In [122]:
from konlpy.tag import Okt

In [123]:
okt = Okt()
token = okt.morphs('나는 자연어 처리를 배운다')
print(token) # 형태소 단위로 나누어짐, 6개의 token

['나', '는', '자연어', '처리', '를', '배운다']


In [125]:
# {나:0, ...배운다)
word2index = {}
for v in token: # v에는 각 형태소들이 들어감 
    if v not in word2index.keys():
        word2index[v] = len(word2index)
print(word2index)
# 각각의 token에 index 부여       

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [127]:
# 원 핫 인코딩
def OHE(word, word2index):
    a = [0]*len(word2index)
    a[word2index[word]] = 1
    return a

In [128]:
OHE('는',word2index)

[0, 1, 0, 0, 0, 0]

In [129]:
text = '나랑 코엑스에 브로슈에 가지러 갈래 갈래 갈래 브로슈어 가지러 가자'

In [130]:
from tensorflow.keras.utils import to_categorical

In [134]:
tok = Tokenizer()
tok
tok.fit_on_texts([text]) # 텍스트 수치화

In [135]:
tok.index_word # index - word

{1: '갈래', 2: '가지러', 3: '나랑', 4: '코엑스에', 5: '브로슈에', 6: '브로슈어', 7: '가자'}

In [143]:
tok.word_index # word - index

{'갈래': 1, '가지러': 2, '나랑': 3, '코엑스에': 4, '브로슈에': 5, '브로슈어': 6, '가자': 7}

In [144]:
text2 = '코엑스에 갈래 브로슈어 가지러 함께 가자 어서'

In [146]:
encoded = tok.texts_to_sequences([text2])[0] #정수 인코딩
encoded
# tok에 '함께,어서'는 없어서 안나옴 

[4, 1, 6, 2, 7]

In [147]:
OH = to_categorical(encoded) # 원 핫 인코딩
OH

array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
# 단어의 갯수가 증가하면 차원도 증가해서 부담
# 저장 효율이 떨어짐
# 유사도 ? 구하기 어려움

# 국어 = [1000]
# 수학 = [0100]
# 과학 = [0010]
# 영어 = [0001]
# 4차원 벡터 
=> 검색어 : 제주도 숙박 (숙식, 호텔, 모텔, 게스트하우스, 잠잘곳...)
문제해결방법? 단어에 의미를 부여하여 벡터화 (word2vec, fasttext, lsa, lda...)

In [ ]:
## 언어 모델
# 단어의 순서에 확률을 적용한 모델 

# 1) 통계적 기법 < 신경망 기법(LSTM, BERT, ... )
# - 통계적 기법 : 단어 등장시 다음 단어를 예측 
# 코로나 ??? 결과가 음성입니다. >> 양쪽 단어를 기반으로 (검사) 중간단어 예측 (BERT)


# 번역
# P(나는 밥을 먹는다) >> P(나는 밥을 마신다)

# 손님 커피가 
# P(나왔습니다) >> P(나오셨습니다)

'손님 ~ 커피가 나오셨습니다'

음성 인식 -> 자막생성 ( 나는 밥을 먹습니다 (50%)) 
나는 밥을 먹습니다 (50%)
나는 날을 먹습니다 (10%)
나는 달을          (0.5%) 