### 단어와 문자의 One Hot Encoding

- 단어 수준 OHE

In [26]:
import numpy as np
samples = ['The cat sat on the mat.', 'The dog ate my homework']

In [27]:
token_index = {}

for sample in samples:
    for word in sample:
        for word in sample.split():
            if word not in token_index:
                token_index[word] = len(token_index) + 1 # zero index 사용x
            #print(word)
            
max_length = 10

# 결과 저장 배열
results = np.zeros((len(samples),
                    max_length,
                    max(token_index.values()) + 1))

for i, sample in enumerate(samples):
#     0 The cat sat on the mat.
#     1 The dog ate my homework
    for j,word in list(enumerate(sample.split()))[:max_length]: # max_length 길이의 list
#         0 The 
#         1 cat
#         2 sat
#         3 on
#         4 the
#         5 mat.

#         0 The
#         1 dog
#         2 ate
#         3 my
#         4 homework
        index = token_index.get(word) # get : key 값 가져옴
        results[i,j,index] = 1
results        

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

첫번째 문장 / 두번째 문장에 대한 행렬

- 문자 수준 OHE

In [62]:
import string
samples = ['The cat sat on the mat.', 'The dog ate my homework']
characters = string.printable # 출력가능한 아스키 문자
token_index= dict(zip(characters, range(1,len(characters)+1)))
# print(token_index)

max_length = 50
results = np.zeros((len(samples),
                        max_length,
                        max(token_index.values())+1))

for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i,j,index]=1

21

In [61]:
results

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Keras를 사용한 단어수준 OHE

In [74]:
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.', 'The dog ate my homework']

tokenizer = Tokenizer(num_words=1000) # 가장 빈도 높은 1000개의 단어만
tokenizer.fit_on_texts(samples) # Doc 바탕 단어 인덱스 구축

sequences = tokenizer.texts_to_sequences(samples) # 문자열 >>> 정수index list
print(sequences)
print('-'*50)
one_hot_results = tokenizer.texts_to_matrix(samples,mode='binary') # One Hot 이진 벡터
print(one_hot_results)
print('-'*50)
word_index = tokenizer.word_index
print(word_index)
print('-'*50)
print('{}개의 고유한 토큰'.format(len(word_index)))

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
--------------------------------------------------
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
--------------------------------------------------
{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}
--------------------------------------------------
9개의 고유한 토큰


### Hashing을 이용한 단어수준 OHE

In [75]:
samples = ['The cat sat on the mat.', 'The dog ate my homework']
dimensionality = 1000 # 단어 크기가 1000인 벡터 or 그 이상 이라면 hashing 충돌이 늘어나고 인코딩 정확도 감소
max_length = 10

results = np.zeros((len(samples),max_length,dimensionality)) # sample 갯수만큼 3차원 행렬
for i,sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = abs(hash(word)) % dimensionality # 단어를 해싱해서 0~1000 사이의 random 정수 index 변환
        results[i,j,index] = 1

In [76]:
results

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])