In [ ]:
'''
시리즈(Series), 데이터 프레임(DataFrame)

시리즈 : 1차원 배열(열 벡터), 배열로부터 생성, 데이터프레임으로부터 생성
'''

In [4]:
import pandas as pd

In [9]:
obj = pd.Series([4,5,1,2])

In [10]:
obj.values

array([4, 5, 1, 2], dtype=int64)

In [11]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
# 내가 부여한 index를 쓰고 싶다면?
obj2 = pd.Series([4,5,1,2],index=['d','b','a','c'])
obj2

d    4
b    5
a    1
c    2
dtype: int64

In [14]:
import numpy as np
x = np.array([4,5,1,2])
x

array([4, 5, 1, 2])

In [16]:
obj2['d']

4

In [17]:
obj2['a']

1

In [18]:
obj2['c']

2

In [19]:
obj2[['c','a','d']] # 동시에 여러개의 데이터 참조 가능

c    2
a    1
d    4
dtype: int64

In [20]:
obj2 > 1

d     True
b     True
a    False
c     True
dtype: bool

In [21]:
obj2[obj2>1]

d    4
b    5
c    2
dtype: int64

In [22]:
obj2*2 # 벡터화 연산 가능

d     8
b    10
a     2
c     4
dtype: int64

In [23]:
np.exp(obj2)

d     54.598150
b    148.413159
a      2.718282
c      7.389056
dtype: float64

In [24]:
np.max(obj2)

5

In [27]:
# 시리즈는 딕셔너리와 유사, 시리즈는 인덱스에 데이터가 매핑
# 시리즈는 딕셔너리 대신하여 사용
obj2
'b' in obj2
'z' in obj2

False

In [30]:
# 딕셔너리 -> 시리즈 생성
cdata = {'Seoul':1000, 'Incheon':200, 'Busan':300, 'Gwangju':100}
cdata
obj3 = pd.Series(cdata)
obj3 # 딕셔너리의 key가 인덳스 / 딕셔너리 value가 value로

Seoul      1000
Incheon     200
Busan       300
Gwangju     100
dtype: int64

In [33]:
cdata2 =['Suwon','Incheon','Busan','Gwangju']

In [36]:
obj4 = pd.Series(cdata, index=cdata2) # cdata2의 를 인덱스로 시리즈 data는 cdata
obj4 
# Nan : 판다스에서는 누락값 또는 NA라고도 함
# isnull, notnull 함수를 이용하여 누락값을 찾을 수 있음

pd.isnull(obj4)
pd.notnull(obj4)

Suwon      False
Incheon     True
Busan       True
Gwangju     True
dtype: bool

In [37]:
obj3

Seoul      1000
Incheon     200
Busan       300
Gwangju     100
dtype: int64

In [38]:
obj4

Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
dtype: float64

In [39]:
obj3 + obj4 # index 같은 애들끼리 함쳐짐

Busan      600.0
Gwangju    200.0
Incheon    400.0
Seoul        NaN
Suwon        NaN
dtype: float64

In [45]:
obj4
obj4.name='population' # 이름을 줄 수 있음
obj4

Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
Name: population, dtype: float64

In [46]:
obj4.index.name = 'city'
obj4 # index에 city라는 이름이 붙음

city
Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
Name: population, dtype: float64

In [47]:
obj

0    4
1    5
2    1
3    2
dtype: int64

In [48]:
obj
obj.index = ['k','a','j','b'] # 새로운 인덱스 부여 
obj

k    4
a    5
j    1
b    2
dtype: int64

In [49]:
# 데이터 프레임 : 서로 다른 종류의 데이터를 담을 수 있다. (엑셀 시트 개념과 유사)
a = [1,2,3.14,'a'] # list는 타입이 달라도 상관없, 어떤것이든 다 저장 가능
a

[1, 2, 3.14, 'a']

In [50]:
arr = np.array(a)
arr

array(['1', '2', '3.14', 'a'], dtype='<U32')

In [59]:
# dataframe 예시
data = {'city':['Seoul','Daegu','Busan','Gwangju'], # 열벡터(시리즈)
       'year':[2000,2001,2003,2002],
       'pop':[0.9,0.2,0.3,0.1]} # 열벡터(시리즈)
df = pd.DataFrame(data)
df
# type(df)


city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [57]:
df.city; df['city'] # 참조

0      Seoul
1      Daegu
2      Busan
3    Gwangju
Name: city, dtype: object

In [62]:
type(df['city']) # 열 하나는 시리즈 타입
df['city']

0      Seoul
1      Daegu
2      Busan
3    Gwangju
Name: city, dtype: object

In [61]:
type(df['pop']) # 시리즈 타입
df['pop'] # float

0    0.9
1    0.2
2    0.3
3    0.1
Name: pop, dtype: float64

In [ ]:
# int64= -922경 ~ +922경
# float32 =-3.4*10의 38승 ~ 3.4*10의 38승
# float64 = -1.78*10dml 308승 ~ 1.78*10dml 308승


In [63]:
df

city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [67]:
# 내가 원하는 순서로
df = pd.DataFrame(data)
pd.DataFrame(data, columns=['year','city','pop'])

year     city  pop
0  2000    Seoul  0.9
1  2001    Daegu  0.2
2  2003    Busan  0.3
3  2002  Gwangju  0.1

In [68]:
pd.DataFrame(data, columns=['year','city','pop','loc']) # loc 열은 있지만 값은 없어서 Nan

year     city  pop  loc
0  2000    Seoul  0.9  NaN
1  2001    Daegu  0.2  NaN
2  2003    Busan  0.3  NaN
3  2002  Gwangju  0.1  NaN

In [70]:
df2 = pd.DataFrame(data, columns=['year','city','pop','location'],
                  index=['one','two','three','four'])
df2

year     city  pop location
one    2000    Seoul  0.9      NaN
two    2001    Daegu  0.2      NaN
three  2003    Busan  0.3      NaN
four   2002  Gwangju  0.1      NaN

In [74]:
#df2[0] 키에러
df2.loc['two'] # two 인덱스를 가진 데이터가 추출
df2['city'] #  city 열 추출

one        Seoul
two        Daegu
three      Busan
four     Gwangju
Name: city, dtype: object

In [76]:
df2.iloc[0] #  묵시적으로 행 인덱스가 0번부터 부여되어 있음
#df2.loc[0] # loc는 명시적인 행 인덱스 명이 와야 함

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [ ]:
df3.loc[11] # 명시적 행 인덱스명  > > 일종의 행 라벨을 가지고 검색
df3.iloc[] # 묵시적 행 인덱스명 

In [ ]:
df3.loc[12]
df3.iloc[2]

In [ ]:
# 행 인덱스 명으로 데이터 검색(추출) : loc
# 묵시적(고유,절대적) 행 인덱스 명으로 데이터 검색(추출) : iloc

In [77]:
df2

year     city  pop location
one    2000    Seoul  0.9      NaN
two    2001    Daegu  0.2      NaN
three  2003    Busan  0.3      NaN
four   2002  Gwangju  0.1      NaN

In [79]:
df2['location'] 

one      NaN
two      NaN
three    NaN
four     NaN
Name: location, dtype: object

In [80]:
df2['location']=126.0
df2

year     city  pop  location
one    2000    Seoul  0.9     126.0
two    2001    Daegu  0.2     126.0
three  2003    Busan  0.3     126.0
four   2002  Gwangju  0.1     126.0

In [81]:
df2['location']=np.arange(4) # 길이가 동일해야함
df2

year     city  pop  location
one    2000    Seoul  0.9         0
two    2001    Daegu  0.2         1
three  2003    Busan  0.3         2
four   2002  Gwangju  0.1         3

In [83]:
val = pd.Series([10,12],index=['one','three'])
val

one      10
three    12
dtype: int64

In [84]:
val.loc['three']

12

In [85]:
val.iloc[1]

12

In [87]:
df2['location'] = val # location column에 val 이 가진 one, three 에 해당하는 값이 들어왔다
df2

year     city  pop  location
one    2000    Seoul  0.9      10.0
two    2001    Daegu  0.2       NaN
three  2003    Busan  0.3      12.0
four   2002  Gwangju  0.1       NaN

In [ ]:
#df2['eastern'] # True/False

In [90]:
(df2.city == 'Daegu')|(df2.city == "Busan")
df2['eastern'] = (df2.city == 'Daegu')|(df2.city == "Busan")
df2

year     city  pop  location  eastern
one    2000    Seoul  0.9      10.0    False
two    2001    Daegu  0.2       NaN     True
three  2003    Busan  0.3      12.0     True
four   2002  Gwangju  0.1       NaN    False

In [91]:
df2.columns

Index(['year', 'city', 'pop', 'location', 'eastern'], dtype='object')

In [92]:
df2.columns
del df2['eastern'] # eastern 열 제거

In [93]:
df2

year     city  pop  location
one    2000    Seoul  0.9      10.0
two    2001    Daegu  0.2       NaN
three  2003    Busan  0.3      12.0
four   2002  Gwangju  0.1       NaN

In [94]:
# 중첩된 딕셔너리 -> 데이터프레임
pop = {'Jeonju':{2001:30, 2002:35}, # key가 행 변수로 옴
      'Daeeon':{2001:80, 2002:90}}  # 
df5 = pd.DataFrame(pop)
df5

Jeonju  Daeeon
2001      30      80
2002      35      90

In [96]:
df5.T

2001  2002
Jeonju    30    35
Daeeon    80    90

In [97]:
pop = {'Jeonju':{2001:30, 2002:35}, # key가 행 변수로 옴
      'Daeeon':{2001:80, 2020:90}}  # 없으면 NaN
df5 = pd.DataFrame(pop)
df5

Jeonju  Daeeon
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [99]:
df5.index.name='year' # 행 인덱스에 이름 부여 
df5

Jeonju  Daeeon
year                
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [100]:
df5.columns.name='city' # 열 인덱스에 이름 부여
df5

city  Jeonju  Daeeon
year                
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [101]:
df5.values
# 데이터 프레임에 저장되어 있는 데이터를 array로 추출하고자 한다면
# 데이터 프레임 변수명.values

array([[30., 80.],
       [35., nan],
       [nan, 90.]])

In [ ]:
pop = {'Jeonju':{2001:30, 2002:35}, # key가 행 변수로 옴
      'Daeeon':{2001:80, 2020:90}}  # 없으면 NaN
df5 = pd.DataFrame(pop)
df5

In [105]:
obj = pd.Series(range(11,14),index=['a','b','c'])
index = obj.index
index[0]

'a'

In [107]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
# index[1]= 'd ' 에러 / 인덱스는 변경이 안됨

In [109]:
labels = pd.Index(np.arange(100,103))
labels

Int64Index([100, 101, 102], dtype='int64')

In [ ]:
# label(레이블(y))
# x입력데이터 --> 모델 --> y출력데이터(모델 예측값, yhat), 실제 정답데이터(y))
#
# label(라벨, 인덱스)

In [112]:
obj2 = pd.Series([1.0,-2.0,0], index=labels) # labels가 인덱스 번호로 들어감
obj2 

100    1.0
101   -2.0
102    0.0
dtype: float64

In [113]:
obj2.index is labels # 서로 같은지 확인 ( 같은 객체 인지?)

True

In [126]:
'city' in df2.columns # city 컬럼이 있는지 확인
11 df2.index # 11번 인덱스가 있는지 확인

SyntaxError: invalid syntax (<ipython-input-126-a76015d5b15d>, line 2)

In [127]:
# 재색인(re indexing)
obj = pd.Series([4.1,7.1,-5.5,3.3], index=['d','b','a','c'])
obj # 인덱스 나열 순으로 저장됨

d    4.1
b    7.1
a   -5.5
c    3.3
dtype: float64

In [128]:
obj2 = obj.reindex(['a','b','c','d'])
obj2

a   -5.5
b    7.1
c    3.3
d    4.1
dtype: float64

In [130]:
obj2 = obj.reindex(['a','b','c','d','e']) #없으면 nan
obj2

a   -5.5
b    7.1
c    3.3
d    4.1
e    NaN
dtype: float64

In [ ]:
# 시계열 데이터 재색인 -> 보간(채움)
# 매출데이터 > 날씨 온도 주문시각....


# 앙상블 기법
# 200 200 300 100 100

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'],method='ffill') #없으면 nan
obj2

In [132]:
obj3 = pd.Series(['data1','data2','data3'],index=[0,2,4])
obj3

0    data1
2    data2
4    data3
dtype: object

In [133]:
obj3.reindex(range(3))

0    data1
1      NaN
2    data2
dtype: object

In [134]:
obj3.reindex(range(5),method='ffill') # forward방향(위 >> 아래 방향) 으로 fill

0    data1
1    data1
2    data2
3    data2
4    data3
dtype: object

In [135]:
obj3.reindex(range(5),method='bfill') #아래 >> 위 방향으로 fill

0    data1
1    data2
2    data2
3    data3
4    data3
dtype: object

In [136]:
df

city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [137]:
df.loc[[0,2,3],'city']
df.loc[[0,2,3],['city','pop']]

city  pop
0    Seoul  0.9
2    Busan  0.3
3  Gwangju  0.1

In [ ]:
# 행 또는 열 삭제(drop)

In [145]:
obj = pd.Series(np.arange(11,16), index=['a','b','c','d','e'])
obj
#del obj['c']
# newobj = obj.drop('c') ;newobj

a    11
b    12
e    15
dtype: int32

In [144]:
newobj = obj.drop(['c','d'])
newobj

a    11
b    12
e    15
dtype: int32

In [169]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['Gwangju','Seoul','Jeju','Busan'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Gwangju    0    1      2     3
Seoul      4    5      6     7
Jeju       8    9     10    11
Busan     12   13     14    15

In [170]:
data.drop(['Seoul','Busan'])

one  two  three  four
Gwangju    0    1      2     3
Jeju       8    9     10    11

In [171]:
data

one  two  three  four
Gwangju    0    1      2     3
Seoul      4    5      6     7
Jeju       8    9     10    11
Busan     12   13     14    15

In [172]:
#two 라는 열 제거 axis = 1
data.drop('two',axis=1) # default >> axis=0
data.drop('two',axis='columns',inplace=True) # 내부적으로 값이 저장

one  two  three  four
Gwangju    0    1      2     3
Seoul      4    5      6     7
Jeju       8    9     10    11
Busan     12   13     14    15

In [174]:
data

one  three  four
Gwangju    0      2     3
Seoul      4      6     7
Jeju       8     10    11
Busan     12     14    15

In [176]:
df =pd.read_csv('test_csv_file.csv')

In [177]:
type(df)

pandas.core.frame.DataFrame

In [190]:
df = pd.read_csv('test_text_file.txt',sep='|',index_col='ID')# index_col >> 인덱스로 사용하고자 할 컬럼
df

A  B  C  D
ID            
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [191]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [192]:
pd.read_csv('gapminder.tsv',sep='\t') 

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [ ]:
pd.read_csv('test_text_file.txt',sep='|',index_col='ID')# index_col >> 인덱스로 사용하고자 할 컬럼

In [202]:
pd.read_csv('text_without_column_name.txt',sep='|',header=None,
           names=['ID','A','B','C','D'], index_col='ID')

A  B  C  D
ID            
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [209]:
pd.read_csv('test_csv_file.csv',skiprows=3,header=None)

0     1   2
0  3   LEE  41
1  4  PARK  19
2  5   LIM  36

In [212]:
pd.read_csv('test_csv_file.csv',skiprows=[1,2])

ID LAST_NAME  AGE
0   3       LEE   41
1   4      PARK   19
2   5       LIM   36

In [213]:
pd.read_csv('test_csv_file.csv',nrows=3)

ID LAST_NAME  AGE
0   1       KIM   30
1   2      CHOI   25
2   3       LEE   41

In [221]:
df = pd.read_csv('test_text_file.txt',sep='|',na_values=['없음','??','모름'])
print(df)
df.info()

   ID    A    B  C    D
0  C1  1.0  2.0  3  NaN
1  C2  NaN  6.0  7  8.0
2  C3  1.0  NaN  5  7.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      3 non-null      object 
 1   A       2 non-null      float64
 2   B       2 non-null      float64
 3   C       3 non-null      int64  
 4   D       2 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 248.0+ bytes
