In [1]:
import numpy as np

In [5]:
# numpy배열, 동일한 자료형. 원소의 개수를 변경할 수 없음
# 벡터/행렬 - 선형대수연산
# 파이썬 리스트
np.array([1,2,3]) # 1차원 배열
type(np.array([1,2,3])) # list 처럼 보이지만 아님 (array)

numpy.ndarray

In [7]:
data = np.array([1,2,3])*2
data

array([2, 4, 6])

In [8]:
(data==4) | (data>2) # 벡터화 연산, 2보다 큰 것과 4가 있는지 확인

array([False,  True,  True])

In [11]:
c = np.array([[1,2,3],[4,5,6]]) # 다차원 배열 구조 (2차원 >> 행렬, 1차원 >> 벡터)
c # 2행 3열 2x3 행렬
len(c)
len(c[0])

3

In [13]:
d = np.array(list(range(24))).reshape(2,3,4) # 3차원 배열 행, 열, 깊이 2*3*4배열
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
d.ndim # dimension
d.shape # 배열크기

(2, 3, 4)

In [17]:
# 배열 인덱싱, 슬라이싱
a = np.array([2,3,4,5,6])
a[2]
a[-2]

5

In [18]:
# 다차원 배열의 경우에는 컴마를 사용, 컴마로 구분된 차원을 축(axis)
a = np.array([[1,2,3],
         [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0,0]
a[-1,-1] #6

6

In [30]:
# 슬라이싱
# 첫번째 행을 참조하는 서로 다른 방법
a[0]
a[0,:]
a[:1,:1] # 0번행의 0번열 의미

array([[1]])

In [79]:
a[:-1]

array([[1, 2, 3]])

In [ ]:
# 팬시 인덱싱

In [80]:
names = np.array(['Bob', 'Joe', 'Bob', 'Will'])
data = np.random.randn(4,4) # 표준 정규분포에서 난수 발생

In [81]:
names
data

array([[-0.70405761, -0.0515508 , -1.25530924, -2.08080379],
       [ 0.1061224 , -0.09386353,  0.04667463,  0.86655131],
       [ 2.1185653 , -0.76631706, -0.06862425, -1.32786223],
       [ 0.48760992,  1.04483664, -1.91912222,  0.35578435]])

In [82]:
names == "Bob" # boolean 참조

array([ True, False,  True, False])

In [83]:
data[names=='Bob']

array([[-0.70405761, -0.0515508 , -1.25530924, -2.08080379],
       [ 2.1185653 , -0.76631706, -0.06862425, -1.32786223]])

In [84]:
data[names=='Bob',2:] # 2번에서 마지막 인덱스까지

array([[-1.25530924, -2.08080379],
       [-0.06862425, -1.32786223]])

In [85]:
names != 'Bob' # (1)

array([False,  True, False,  True])

In [86]:
~(names=='Bob') # 조건 반대로 (2)

array([False,  True, False,  True])

In [87]:
cond=names == 'Bob'

In [88]:
data[~cond] # Bob 이 아닌 사람만 출력

array([[ 0.1061224 , -0.09386353,  0.04667463,  0.86655131],
       [ 0.48760992,  1.04483664, -1.91912222,  0.35578435]])

In [89]:
mask = (names =='Bob')|(names=='Will')
mask

array([ True, False,  True,  True])

In [90]:
data[mask]

array([[-0.70405761, -0.0515508 , -1.25530924, -2.08080379],
       [ 2.1185653 , -0.76631706, -0.06862425, -1.32786223],
       [ 0.48760992,  1.04483664, -1.91912222,  0.35578435]])

In [91]:
data

array([[-0.70405761, -0.0515508 , -1.25530924, -2.08080379],
       [ 0.1061224 , -0.09386353,  0.04667463,  0.86655131],
       [ 2.1185653 , -0.76631706, -0.06862425, -1.32786223],
       [ 0.48760992,  1.04483664, -1.91912222,  0.35578435]])

In [92]:
data[data < 0] = 0

In [93]:
data # 음수들이 0으로 치환됨

array([[0.        , 0.        , 0.        , 0.        ],
       [0.1061224 , 0.        , 0.04667463, 0.86655131],
       [2.1185653 , 0.        , 0.        , 0.        ],
       [0.48760992, 1.04483664, 0.        , 0.35578435]])

In [94]:
print(names)
print(data)

['Bob' 'Joe' 'Bob' 'Will']
[[0.         0.         0.         0.        ]
 [0.1061224  0.         0.04667463 0.86655131]
 [2.1185653  0.         0.         0.        ]
 [0.48760992 1.04483664 0.         0.35578435]]


In [95]:
# Bob을 제외한 모든 사람들의 데이터를 10으로
data[names != 'Bob'] =10
data

array([[ 0.       ,  0.       ,  0.       ,  0.       ],
       [10.       , 10.       , 10.       , 10.       ],
       [ 2.1185653,  0.       ,  0.       ,  0.       ],
       [10.       , 10.       , 10.       , 10.       ]])

In [111]:
arr = np.empty((8,4))
arr
for i in range(8): # 행단위로 i 값 저장
    arr[i]= i
arr    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [112]:
arr[[4,3,0,6]] # 참조하려는 행이 여러개라면 여러개의 행에대한 번호의 list를 준다 [4,3]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [117]:
arr[[-4,-5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [118]:
np.arange(32)  #  == np.array(list(range(32)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [121]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [122]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [127]:
arr[[1,5,7,2]][:,[0,3,1,2]] # 0,3,1,2 번열을 참조해라

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [128]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
# 전치연산 : 행과 열을 바꾸는 연산
# 벡터의 내적
arr.T #np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [130]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [131]:
# 사이킷런 : 머신러닝 알고리즘들이 구현되어 있는 패키지(싸이킷런)
from sklearn.datasets import load_iris
iris = load_iris()
np.shape(iris['data']) # 150개의 데이터
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [132]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [136]:
iris.data[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
# 벡터 ? 여러개의 숫자가 특정한 순서대로 모여있는것 
# 꽃받침 길이. 폭. 꽃잎길이. 폭
# 크기 : [5.1, 3.5, 1.4, 0.2]
# 붓꽃의 크기 벡터는 4개의 데이터가 하나로 묶여있는 구조
# 벡터를 구성하는 data가 4개 = > 4차원 벡터 

In [137]:
# numpy 벡터 표현
# 벡터는 열의 개수가 1갱니 2차원 배열 객체로 표현
# 배열의 차원은 벡터의 차원과 다름
x = np.array([[5.5],
             [3.4],    # 2차원 배열, 열은 1개 
             [1.2],    # 벡터로는 4차원 벡터 
             [0.1]])   # 4차원 벡터를 2차원 배열로 표현 

x

array([[5.5],
       [3.4],
       [1.2],
       [0.1]])

In [138]:
x = np.array([5.5,3.4,1.2,0.1])
x
# 1차원 배열, 벡터
# 사이킷 런에서 벡터를 정의하고자 하는 경우에는
# 반드시 열의 개수가 1개인 2차원 배열로 표현해야 한다

array([5.5, 3.4, 1.2, 0.1])

In [143]:
a = np.arange(12)
a
k = []
for i in range(1,len(a)):
    if (a[i]%2 == 0):
        k.append(a[i])
print(k)
a[a%2 == 0]

[2, 4, 6, 8, 10]


array([ 0,  2,  4,  6,  8, 10])

In [142]:
# numpy 배열 (ndarray) 
# 데이터가 반드시 같은 자료형이어야 한다

array([ 0,  2,  4,  6,  8, 10])

In [146]:
x = np.array([1,2,3.0])
x 
x.dtype # 정수도, 실수도 있으면 실수

dtype('float64')

In [151]:
x = np.array([1,2,3],dtype='f') # dtype 정할 수 있다. u >> unsined int / U >>> unicode(3byte)
x.dtype

dtype('float32')

In [152]:
x = np.array([1,2],dtype='f')
x

array([1., 2.], dtype=float32)

In [155]:
x = np.array(['1','2'],dtype='U')
x
x[0] + x[1]

'12'

In [156]:
# 무한대 : np.inf
np.inf
# 정의할 수 없는 숫자 : Nan (Not a number)

inf

In [157]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

<ipython-input-157-dc768ac6b521>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
<ipython-input-157-dc768ac6b521>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [158]:
print(np.exp(-np.inf))

0.0


In [159]:
# 유니버설 함수 : ndarray 데이터를 원소별로 연산을 수행하는 함수
# 스칼라값 -> 스칼라값 리턴하는 벡터화된 래퍼 함수
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
np.sqrt(arr)
np.exp(arr) # 자연상수 e:2.71828...

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [161]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print(np.maximum(x,y)) # 두 array의 요소 끼리 비교를 해서 큰값을 선택

[-1.29746598  0.82286894 -1.58830744  0.35578616  0.00260922  0.474326
  1.5590456   1.465831  ]
[-0.35136896  0.97674067  0.36633483 -1.22056246 -1.4681963   0.81084397
 -0.53967301  0.72471364]
[-0.35136896  0.97674067  0.36633483  0.35578616  0.00260922  0.81084397
  1.5590456   1.465831  ]


In [162]:
arr = np.random.randn(7)*5
print(arr)
remainder, whold_part=np.modf(arr) # remainder에는 나머지 (modf), whold_part에는 몫
print(remainder)
whold_part

[ 7.21607236 -3.79132391 -4.09359019 -6.18682918  3.54636458  3.28288654
 -2.200035  ]
[ 0.21607236 -0.79132391 -0.09359019 -0.18682918  0.54636458  0.28288654
 -0.200035  ]


array([ 7., -3., -4., -6.,  3.,  3., -2.])

In [5]:
divmod(7,3) # 몫/나머지

(2, 1)

In [12]:
np.zeros(5)
np.zeros((3,5),dtype='i')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [15]:
np.ones((2,3,4),dtype='i')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [17]:
x = np.zeros((3,4))

In [18]:
y = np.ones_like(x) # y=np.ones((3,4)) x라는 변수의 형상(3,4)을 그대로 사용, 1로 초기화 해라
y  # 뒤에 like가 붙으면 괄호안 의 변수와 같이 형상을 가짐

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.empty((4,3)) # empty : 배열 생성만하고 초기화 작업은 하지 않는 명령 , 배열 생성에만 의미
a  # 지금 값은 기존에 있던 값들 ( 초기화 안했으므로)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,100,5) # 시작 , 끝, 갯수 #선형공간 linear + space

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [27]:
a = np.arange(12)
a
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.reshape(3,-1) # -1 : 니가 알아서 계산해서 대체 # a는 12니까, 3으로 나누면 4네??? >>> 알아서 열 계산
a.reshape(-1,3)
a.reshape(2,2,-1)
a.reshape(2,-1,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
a = a.reshape(3,4)

In [34]:
a.flatten() # 다차원 배열을 1차원 배열로

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ravel() # 위와 같음

In [35]:
x = np.arange(5) # 1차원 배열
x

array([0, 1, 2, 3, 4])

In [39]:
# 배열의 1차원 증가 : newaxis (차원을 증가시킬 때 쓰는 함수)
x
x[:,np.newaxis] 

array([[0],
       [1],
       [2],
       [3],
       [4]])