In [2]:
import pandas as pd
import numpy as np

In [3]:
visited = pd.read_csv('C:/Users/USER/Desktop/dataset/deepL/data_merge_exdata/survey_visited.csv') 
survey = pd.read_csv('C:/Users/USER/Desktop/dataset/deepL/data_merge_exdata/survey_survey.csv')

In [4]:
visited

ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [5]:
survey

taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [7]:
# Visited와 Survey Merge
vs = visited.merge(survey, left_on='ident',right_on='taken')
vs

ident   site       dated  taken person quant  reading
0     619   DR-1  1927-02-08    619   dyer   rad     9.82
1     619   DR-1  1927-02-08    619   dyer   sal     0.13
2     622   DR-1  1927-02-10    622   dyer   rad     7.80
3     622   DR-1  1927-02-10    622   dyer   sal     0.09
4     734   DR-3  1939-01-07    734     pb   rad     8.41
5     734   DR-3  1939-01-07    734   lake   sal     0.05
6     734   DR-3  1939-01-07    734     pb  temp   -21.50
7     735   DR-3  1930-01-12    735     pb   rad     7.22
8     735   DR-3  1930-01-12    735    NaN   sal     0.06
9     735   DR-3  1930-01-12    735    NaN  temp   -26.00
10    751   DR-3  1930-02-26    751     pb   rad     4.35
11    751   DR-3  1930-02-26    751     pb  temp   -18.50
12    751   DR-3  1930-02-26    751   lake   sal     0.10
13    752   DR-3         NaN    752   lake   rad     2.19
14    752   DR-3         NaN    752   lake   sal     0.09
15    752   DR-3         NaN    752   lake  temp   -16.00
16    752   DR-3         NaN    752    roe   sal    41.60
17    837  MSK-4  1932-01-14    837   lake   rad     1.46
18    837  MSK-4  1932-01-14    837   lake   sal     0.21
19    837  MSK-4  1932-01-14    837    roe   sal    22.50
20    844   DR-1  1932-03-22    844    roe   rad    11.25

In [8]:
num = pd.Series({'dog':4, 'amoeba':np.nan})
print(num)
# dog / amoeba는 index / 4.0, nan이 data
# series는 열 이름이 없다

dog       4.0
amoeba    NaN
dtype: float64


In [9]:
gapminder = pd.read_csv('C:/Users/USER/Desktop/dataset/deepL/pandas_data/gapminder.tsv',sep='\t')
gapminder

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [10]:
# Country로 groupby, pop에대한 평균

print(gapminder.groupby(['country'])['pop'].mean())
print('='*50)
print(gapminder.groupby(['country'])['pop'].max())
print('='*50)
print(gapminder.groupby(['continent'])['gdpPercap'].mean())

country
Afghanistan           1.582372e+07
Albania               2.580249e+06
Algeria               1.987541e+07
Angola                7.309390e+06
Argentina             2.860224e+07
                          ...     
Vietnam               5.456857e+07
West Bank and Gaza    1.848606e+06
Yemen, Rep.           1.084319e+07
Zambia                6.353805e+06
Zimbabwe              7.641966e+06
Name: pop, Length: 142, dtype: float64
country
Afghanistan           31889923
Albania                3600523
Algeria               33333216
Angola                12420476
Argentina             40301927
                        ...   
Vietnam               85262356
West Bank and Gaza     4018332
Yemen, Rep.           22211743
Zambia                11746035
Zimbabwe              12311143
Name: pop, Length: 142, dtype: int64
continent
Africa       2193.754578
Americas     7136.110356
Asia         7902.150428
Europe      14469.475533
Oceania     18621.609223
Name: gdpPercap, dtype: float64


In [11]:
# 각 연도별 grouping 후 그룹단위 기대수명
life_exp = gapminder.groupby(['year'])['lifeExp'].mean()
life_exp

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [14]:
# 2002년도 값
life_exp.iloc[10]
life_exp.iloc[-2]
life_exp.loc[2002]

65.69492253521126

In [16]:
life_exp.loc[2000:2008]

print(life_exp.index)
life_exp[life_exp.index > 2000]

Int64Index([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
            2007],
           dtype='int64', name='year')


year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [17]:
ebola = pd.read_csv('C:/Users/USER/Desktop/dataset/deepL/pandas_data/country_timeseries.csv')

In [18]:
# ebola의 전체 컬럼명 확인
ebola.columns

Index(['Date', 'Day', 'Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates', 'Cases_Spain',
       'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia', 'Deaths_SierraLeone',
       'Deaths_Nigeria', 'Deaths_Senegal', 'Deaths_UnitedStates',
       'Deaths_Spain', 'Deaths_Mali'],
      dtype='object')

In [19]:
len(ebola.columns)
ebola.info
ebola.count()

Date                   122
Day                    122
Cases_Guinea            93
Cases_Liberia           83
Cases_SierraLeone       87
Cases_Nigeria           38
Cases_Senegal           25
Cases_UnitedStates      18
Cases_Spain             16
Cases_Mali              12
Deaths_Guinea           92
Deaths_Liberia          81
Deaths_SierraLeone      87
Deaths_Nigeria          38
Deaths_Senegal          22
Deaths_UnitedStates     18
Deaths_Spain            16
Deaths_Mali             12
dtype: int64

In [21]:
ebola.shape[0] - ebola.count() # 스칼라 - 시리즈

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [23]:
ebola.isnull().sum()
ebola.isnull().sum(axis = 1) # 행 단위로 결측값

0      12
1      12
2      10
3      14
4      10
       ..
117    10
118    14
119    14
120    14
121    14
Length: 122, dtype: int64

In [26]:
ebola.fillna(0)
ebola.fillna(method='ffill')
ebola.interpolate()

Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
0      1/5/2015  289        2776.0            NaN            10030.0   
1      1/4/2015  288        2775.0            NaN             9780.0   
2      1/3/2015  287        2769.0         8166.0             9722.0   
3      1/2/2015  286        2749.5         8157.0             9677.5   
4    12/31/2014  284        2730.0         8115.0             9633.0   
..          ...  ...           ...            ...                ...   
117   3/27/2014    5         103.0            8.0                6.0   
118   3/26/2014    4          86.0            8.0                6.0   
119   3/25/2014    3          86.0            8.0                6.0   
120   3/24/2014    2          86.0            8.0                6.0   
121   3/22/2014    0          49.0            8.0                6.0   

     Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  \
0              NaN            NaN                 NaN          NaN   
1              NaN            NaN                 NaN          NaN   
2              NaN            NaN                 NaN          NaN   
3              NaN            NaN                 NaN          NaN   
4              NaN            NaN                 NaN          NaN   
..             ...            ...                 ...          ...   
117            0.0            1.0                 1.0          1.0   
118            0.0            1.0                 1.0          1.0   
119            0.0            1.0                 1.0          1.0   
120            0.0            1.0                 1.0          1.0   
121            0.0            1.0                 1.0          1.0   

     Cases_Mali  Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  \
0           NaN         1786.0             NaN              2977.0   
1           NaN         1781.0             NaN              2943.0   
2           NaN         1767.0          3496.0              2915.0   
3           NaN         1753.0          3496.0              2871.0   
4           NaN         1739.0          3471.0              2827.0   
..          ...            ...             ...                 ...   
117         1.0           66.0             6.0                 5.0   
118         1.0           62.0             6.0                 5.0   
119         1.0           60.0             6.0                 5.0   
120         1.0           59.0             6.0                 5.0   
121         1.0           29.0             6.0                 5.0   

     Deaths_Nigeria  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  \
0               NaN             NaN                  NaN           NaN   
1               NaN             NaN                  NaN           NaN   
2               NaN             NaN                  NaN           NaN   
3               NaN             NaN                  NaN           NaN   
4               NaN             NaN                  NaN           NaN   
..              ...             ...                  ...           ...   
117             0.0             0.0                  0.0           1.0   
118             0.0             0.0                  0.0           1.0   
119             0.0             0.0                  0.0           1.0   
120             0.0             0.0                  0.0           1.0   
121             0.0             0.0                  0.0           1.0   

     Deaths_Mali  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
..           ...  
117          1.0  
118          1.0  
119          1.0  
120          1.0  
121          1.0  

[122 rows x 18 columns]

In [27]:
ebola.dropna() # 결측값 있는 모든 행 삭제

Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
19  11/18/2014  241        2047.0         7082.0             6190.0   

    Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  Cases_Mali  \
19           20.0            1.0                 4.0          1.0         6.0   

    Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  Deaths_Nigeria  \
19         1214.0          2963.0              1267.0             8.0   

    Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali  
19             0.0                  1.0           0.0          6.0

In [28]:
ebola.dropna(axis=1) # 결측값 있는 모든 열 삭제

Date  Day
0      1/5/2015  289
1      1/4/2015  288
2      1/3/2015  287
3      1/2/2015  286
4    12/31/2014  284
..          ...  ...
117   3/27/2014    5
118   3/26/2014    4
119   3/25/2014    3
120   3/24/2014    2
121   3/22/2014    0

[122 rows x 2 columns]

In [36]:
print(ebola.loc[1])
print(ebola.loc[1,:])
print(ebola.iloc[1,0:3])
ebola.loc[1,['Date','Day','Cases_Guinea']]
ebola.loc[1,'Date':'Cases_Guinea']
# ebola.loc[1,0:3] error

Date                   1/4/2015
Day                         288
Cases_Guinea             2775.0
Cases_Liberia               NaN
Cases_SierraLeone        9780.0
Cases_Nigeria               NaN
Cases_Senegal               NaN
Cases_UnitedStates          NaN
Cases_Spain                 NaN
Cases_Mali                  NaN
Deaths_Guinea            1781.0
Deaths_Liberia              NaN
Deaths_SierraLeone       2943.0
Deaths_Nigeria              NaN
Deaths_Senegal              NaN
Deaths_UnitedStates         NaN
Deaths_Spain                NaN
Deaths_Mali                 NaN
Name: 1, dtype: object
Date                   1/4/2015
Day                         288
Cases_Guinea             2775.0
Cases_Liberia               NaN
Cases_SierraLeone        9780.0
Cases_Nigeria               NaN
Cases_Senegal               NaN
Cases_UnitedStates          NaN
Cases_Spain                 NaN
Cases_Mali                  NaN
Deaths_Guinea            1781.0
Deaths_Liberia              NaN
Deaths_SierraLeon

Date            1/4/2015
Day                  288
Cases_Guinea      2775.0
Name: 1, dtype: object

In [38]:
# Cases_Guinea 열의 전체 합 출력
ebola['Cases_Guinea'].sum(skipna=True) # default : skipna

84729.0

In [40]:
# 데이터 정규화 : 각 열 데이터 - 각 열 최소값 / (각 열 최댓값 - 각 열 최솟값)  => 0~1
# 데이터 표준화 : 각 데이터 - 각 열 평균 / (각 열 표준편차)

# numpy, scipy.stats, sklearn
np.random.randint(30,size=5) # 범위 / 난수 갯수
data = np.random.randint(30, size=(6,5)) # 6행 5열

In [41]:
data # 행 = 건수 / 열 = 변수(피쳐)
# data에 대해 표준화(열 단위) : numpy, scipy.stats, sklearn

array([[16, 24,  5, 12, 21],
       [ 8, 23, 13, 25, 28],
       [ 2,  6, 24, 19,  1],
       [16,  2, 19, 23,  0],
       [20,  2,  7,  8,  4],
       [26, 21, 19, 10, 12]])

### 1. numpy로 표준화

In [46]:
print(np.mean(data,axis=0)) # 각 열 평균
print(np.std(data,axis=0)) # 각 열 표준편차
data_std = (data- np.mean(data,axis=0))/np.std(data,axis=0)
data_std

[14.66666667 13.         14.5        16.16666667 11.        ]
[ 7.80313327  9.79795897  6.82519841  6.5170716  10.48808848]


array([[ 0.17087153,  1.1226828 , -1.39190093, -0.63934646,  0.95346259],
       [-0.85435766,  1.02062073, -0.21977383,  1.3554145 ,  1.6208864 ],
       [-1.62327955, -0.71443451,  1.39190093,  0.43475559, -0.95346259],
       [ 0.17087153, -1.1226828 ,  0.65932149,  1.0485282 , -1.04880885],
       [ 0.68348613, -1.1226828 , -1.09886915, -1.25311906, -0.66742381],
       [ 1.45240802,  0.81649658,  0.65932149, -0.94623276,  0.09534626]])

### 2. scipy로 표준화

In [47]:
from scipy.stats import zscore
from sklearn.preprocessing import StandardScaler

In [49]:
print(data_std)
data_zstd = zscore(data)
data_zstd

[[ 0.17087153  1.1226828  -1.39190093 -0.63934646  0.95346259]
 [-0.85435766  1.02062073 -0.21977383  1.3554145   1.6208864 ]
 [-1.62327955 -0.71443451  1.39190093  0.43475559 -0.95346259]
 [ 0.17087153 -1.1226828   0.65932149  1.0485282  -1.04880885]
 [ 0.68348613 -1.1226828  -1.09886915 -1.25311906 -0.66742381]
 [ 1.45240802  0.81649658  0.65932149 -0.94623276  0.09534626]]


array([[ 0.17087153,  1.1226828 , -1.39190093, -0.63934646,  0.95346259],
       [-0.85435766,  1.02062073, -0.21977383,  1.3554145 ,  1.6208864 ],
       [-1.62327955, -0.71443451,  1.39190093,  0.43475559, -0.95346259],
       [ 0.17087153, -1.1226828 ,  0.65932149,  1.0485282 , -1.04880885],
       [ 0.68348613, -1.1226828 , -1.09886915, -1.25311906, -0.66742381],
       [ 1.45240802,  0.81649658,  0.65932149, -0.94623276,  0.09534626]])

In [50]:
StandardScaler().fit_transform(data)

array([[ 0.17087153,  1.1226828 , -1.39190093, -0.63934646,  0.95346259],
       [-0.85435766,  1.02062073, -0.21977383,  1.3554145 ,  1.6208864 ],
       [-1.62327955, -0.71443451,  1.39190093,  0.43475559, -0.95346259],
       [ 0.17087153, -1.1226828 ,  0.65932149,  1.0485282 , -1.04880885],
       [ 0.68348613, -1.1226828 , -1.09886915, -1.25311906, -0.66742381],
       [ 1.45240802,  0.81649658,  0.65932149, -0.94623276,  0.09534626]])

In [ ]:
# 표준화(StandScaler) : 각 열 데이터 - 각 열 평균값 / 각열 데이터의 표준편차
# 표준화(RobustScaler) : 각 열 데이터 - 각열중위수(중앙값) / 각열 데이터의 IQR