In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4,5,1,2])

In [3]:
obj.values

array([4, 5, 1, 2], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# 내가 부여한 인덱스를 쓰고싶다면
obj2 = pd.Series([4,5,1,2],index=['d','b','a','c'])
obj2

d    4
b    5
a    1
c    2
dtype: int64

In [6]:
x = np.array([4,5,1,2])
x

array([4, 5, 1, 2])

In [7]:
obj2['d']

4

In [9]:
obj2[['c','a','d']]

c    2
a    1
d    4
dtype: int64

In [10]:
obj2>1

d     True
b     True
a    False
c     True
dtype: bool

In [11]:
obj2[obj2>1]

d    4
b    5
c    2
dtype: int64

In [12]:
obj2*2 # 벡터화 연산 가능

d     8
b    10
a     2
c     4
dtype: int64

In [13]:
np.exp(obj2)

d     54.598150
b    148.413159
a      2.718282
c      7.389056
dtype: float64

In [14]:
np.max(obj2)

5

In [18]:
# 딕셔너리 -> 시리즈 생성
cdata = {'Seoul':1000, 'Incheon':200, 'Busan':300, 'Gwangju':100}
cdata
obj3 = pd.Series(cdata)
obj3

Seoul      1000
Incheon     200
Busan       300
Gwangju     100
dtype: int64

In [19]:
cdata2 =['Suwon','Incheon','Busan','Gwangju']

In [21]:
obj4 = pd.Series(cdata, index=cdata2)
obj4

Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
dtype: float64

In [23]:
pd.isnull(obj4)
pd.notnull(obj4)

Suwon      False
Incheon     True
Busan       True
Gwangju     True
dtype: bool

In [24]:
obj3 +obj4 # index 같은것 끼리 합쳐짐

Busan      600.0
Gwangju    200.0
Incheon    400.0
Seoul        NaN
Suwon        NaN
dtype: float64

In [27]:
obj4.name = 'population' 이름 부여 가능
obj4

Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
Name: population, dtype: float64

In [28]:
obj4.index.name = 'city'
obj4 # index에 city라는 이름이 붙음

city
Suwon        NaN
Incheon    200.0
Busan      300.0
Gwangju    100.0
Name: population, dtype: float64

In [30]:
obj
obj.index = ['k','a','j','b']
obj # 새로운 인덱스 부여

k    4
a    5
j    1
b    2
dtype: int64

In [31]:
# 데이터 프레임 : 서로 다른 종류의 데이터를 담을 수 있다. (엑셀 시트 개념과 유사)
a = [1,2,3.14,'a'] # list는 타입이 달라도 상관없음. 어떤것이든 다 저장 가능
a

[1, 2, 3.14, 'a']

In [35]:
arr = np.array(a)
arr

array(['1', '2', '3.14', 'a'], dtype='<U32')

In [41]:
# dataframe
data = {'city':['Seoul','Daegu','Busan','Gwangju'], # 열벡터(시리즈)
       'year':[2000,2001,2003,2002],
       'pop':[0.9,0.2,0.3,0.1]} # 열벡터(시리즈)
df = pd.DataFrame(data)
df
#type(df)

city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [43]:
df.city; df['city']

0      Seoul
1      Daegu
2      Busan
3    Gwangju
Name: city, dtype: object

In [44]:
type(df['city']) # 열 하나는 시리즈 타입
df['city'] # object

0      Seoul
1      Daegu
2      Busan
3    Gwangju
Name: city, dtype: object

In [46]:
type(df['pop'])
df['pop'] # float

0    0.9
1    0.2
2    0.3
3    0.1
Name: pop, dtype: float64

In [ ]:
# int64= -922경 ~ +922경
# float32 =-3.4*10의 38승 ~ 3.4*10의 38승
# float64 = -1.78*10dml 308승 ~ 1.78*10dml 308승

In [47]:
df

city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [50]:
# 내가 원하는 순서로
pd.DataFrame(data,columns=['year','city','pop'])

year     city  pop
0  2000    Seoul  0.9
1  2001    Daegu  0.2
2  2003    Busan  0.3
3  2002  Gwangju  0.1

In [51]:
pd.DataFrame(data, columns=['year','city','pop','loc']) # loc 열은 있지만 값은 없어서 Nan

year     city  pop  loc
0  2000    Seoul  0.9  NaN
1  2001    Daegu  0.2  NaN
2  2003    Busan  0.3  NaN
3  2002  Gwangju  0.1  NaN

In [52]:
df2 = pd.DataFrame(data, columns=['year','city','pop','location'],
                  index=['one','two','three','four'])
df2

year     city  pop location
one    2000    Seoul  0.9      NaN
two    2001    Daegu  0.2      NaN
three  2003    Busan  0.3      NaN
four   2002  Gwangju  0.1      NaN

In [56]:
df2.iloc[0] #  묵시적으로 행 인덱스가 0번부터 부여되어 있음
#df2.loc[0] # loc는 명시적인 행 인덱스 명이 와야 함

year         2000
city        Seoul
pop           0.9
location      NaN
Name: one, dtype: object

In [58]:
# 행 인덱스 명으로 데이터 검색(추출) : loc
# 묵시적(고유,절대적) 행 인덱스 명으로 데이터 검색(추출) : iloc

In [59]:
df2

year     city  pop location
one    2000    Seoul  0.9      NaN
two    2001    Daegu  0.2      NaN
three  2003    Busan  0.3      NaN
four   2002  Gwangju  0.1      NaN

In [60]:
df2['location']

one      NaN
two      NaN
three    NaN
four     NaN
Name: location, dtype: object

In [62]:
df2['location'] = 126.0
df2

year     city  pop  location
one    2000    Seoul  0.9     126.0
two    2001    Daegu  0.2     126.0
three  2003    Busan  0.3     126.0
four   2002  Gwangju  0.1     126.0

In [63]:
df2['location'] = np.arange(0,4)
df2

year     city  pop  location
one    2000    Seoul  0.9         0
two    2001    Daegu  0.2         1
three  2003    Busan  0.3         2
four   2002  Gwangju  0.1         3

In [64]:
val = pd.Series([10,12],index=['one','three'])
val

one      10
three    12
dtype: int64

In [66]:
val.loc['three']

12

In [67]:
val.iloc[1]

12

In [68]:
df2['location'] = val # location column에 val 이 가진 one, three 에 해당하는 값이 들어왔다
df2

year     city  pop  location
one    2000    Seoul  0.9      10.0
two    2001    Daegu  0.2       NaN
three  2003    Busan  0.3      12.0
four   2002  Gwangju  0.1       NaN

In [71]:
(df2.city == 'Daegu')|(df2.city == "Busan")
df2['eastern'] = (df2.city == 'Daegu')|(df2.city == "Busan")
df2

year     city  pop  location  eastern
one    2000    Seoul  0.9      10.0    False
two    2001    Daegu  0.2       NaN     True
three  2003    Busan  0.3      12.0     True
four   2002  Gwangju  0.1       NaN    False

In [72]:
df2.columns

Index(['year', 'city', 'pop', 'location', 'eastern'], dtype='object')

In [73]:
df2.columns
del df2['eastern'] # eastern 열 제거

In [74]:
df2

year     city  pop  location
one    2000    Seoul  0.9      10.0
two    2001    Daegu  0.2       NaN
three  2003    Busan  0.3      12.0
four   2002  Gwangju  0.1       NaN

In [77]:
# 중첩된 딕셔너리 -> 데이터프레임
pop = {'Jeonju':{2001:30, 2002:35}, # key가 행 변수로 옴
      'Daeeon':{2001:80, 2002:90}}
df5 = pd.DataFrame(pop)
df5

Jeonju  Daeeon
2001      30      80
2002      35      90

In [78]:
df5.T

2001  2002
Jeonju    30    35
Daeeon    80    90

In [79]:
pop = {'Jeonju':{2001:30, 2002:35}, # Dict의 key가 행 변수로 옴
      'Daeeon':{2001:80, 2020:90}}  # 없으면 NaN
df5 = pd.DataFrame(pop)
df5

Jeonju  Daeeon
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [80]:
df5.columns.name='city' # 열 인덱스에 이름 부여
df5

city  Jeonju  Daeeon
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [81]:
df5.index.name='year' # 행 인덱스에 이름 부여 
df5

city  Jeonju  Daeeon
year                
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [82]:
df5.values
# 데이터 프레임에 저장되어 있는 데이터를 array로 추출하고자 한다면
# 데이터 프레임 변수명.values

array([[30., 80.],
       [35., nan],
       [nan, 90.]])

In [83]:
pop = {'Jeonju':{2001:30, 2002:35}, # key가 행 변수로 옴
      'Daeeon':{2001:80, 2020:90}}  # 없으면 NaN
print(pop)
df5 = pd.DataFrame(pop)
df5

{'Jeonju': {2001: 30, 2002: 35}, 'Daeeon': {2001: 80, 2020: 90}}


Jeonju  Daeeon
2001    30.0    80.0
2002    35.0     NaN
2020     NaN    90.0

In [86]:
obj = pd.Series(range(11,14),index=['a','b','c'])
index = obj.index
index[0]

'a'

In [92]:
index[1:]

Index(['b', 'c'], dtype='object')

In [93]:
# index[1]= 'd ' 에러 / 인덱스는 변경이 안됨

In [94]:
labels = pd.Index(np.arange(100,103))
labels

Int64Index([100, 101, 102], dtype='int64')

In [95]:
# label(레이블(y))
# x입력 데이터 -> 모델 -> y출력데이터(모델 예측값, yhat), 실제 정답데이터(y)
# label(라벨, 인덱스)

In [96]:
obj2 = pd.Series([1.0,-2.0,0], index=labels) # labels가 인덱스 번호로 들어감
obj2

100    1.0
101   -2.0
102    0.0
dtype: float64

In [97]:
obj2.index is labels #서로 같은지 확인

True

In [99]:
'city' in df2.columns # city 컬럼이 있는지 확인
df2.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [102]:
# Re indexing
obj = pd.Series([4.1,7.2,-5.5,3.3],index=['d','b','a','c'])
obj

d    4.1
b    7.2
a   -5.5
c    3.3
dtype: float64

In [104]:
obj2 = obj.reindex(['a','b','c','d'])
obj2

a   -5.5
b    7.2
c    3.3
d    4.1
dtype: float64

In [105]:
obj2 = obj.reindex(['a','b','c','d','e']) #없으면 nan
obj2

a   -5.5
b    7.2
c    3.3
d    4.1
e    NaN
dtype: float64

In [ ]:
# 시계열 데이터 재색인 -> 보간(채움)
# 매출데이터 > 날씨 온도 주문시각....


# 앙상블 기법
# 200 200 300 100 100

In [108]:
obj3 = pd.Series(['data1','data2','data3'],index=[0,2,4])
obj3

0    data1
2    data2
4    data3
dtype: object

In [109]:
obj3.reindex(range(3))

0    data1
1      NaN
2    data2
dtype: object

In [110]:
obj3.reindex(range(5),method='ffill') # forward방향(위 >> 아래 방향) 으로 fill

0    data1
1    data1
2    data2
3    data2
4    data3
dtype: object

In [111]:
obj3.reindex(range(5),method='bfill') #아래 >> 위 방향으로 fill

0    data1
1    data2
2    data2
3    data3
4    data3
dtype: object

In [112]:
df

city  year  pop
0    Seoul  2000  0.9
1    Daegu  2001  0.2
2    Busan  2003  0.3
3  Gwangju  2002  0.1

In [119]:
df.loc[[0,2,3],'city']
df.loc[[0,2,3],['city','pop']]

city  pop
0    Seoul  0.9
2    Busan  0.3
3  Gwangju  0.1

In [ ]:
# 행 또는 열 삭제(drop)

In [128]:
obj = pd.Series(np.arange(11,16), index=['a','b','c','d','e'])
obj
# del obj['c']
# newobj = obj.drop('c') ;newobj

a    11
b    12
d    14
e    15
dtype: int32

In [130]:
newobj = obj.drop(['c','d'])
newobj

a    11
b    12
e    15
dtype: int32

In [131]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['Gwangju','Seoul','Jeju','Busan'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Gwangju    0    1      2     3
Seoul      4    5      6     7
Jeju       8    9     10    11
Busan     12   13     14    15

In [132]:
data.drop(['Seoul','Busan'])

one  two  three  four
Gwangju    0    1      2     3
Jeju       8    9     10    11

In [133]:
data

one  two  three  four
Gwangju    0    1      2     3
Seoul      4    5      6     7
Jeju       8    9     10    11
Busan     12   13     14    15

In [137]:
#two 라는 열 제거 axis = 1
data.drop('two',axis=1) # default >> axis=0
data.drop('two',axis='columns',inplace=True) # 내부적으로 값이 저장

In [138]:
data

one  three  four
Gwangju    0      2     3
Seoul      4      6     7
Jeju       8     10    11
Busan     12     14    15